# Generated by Django 4.0.1 on 2022-01-19 16:13

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес магазина')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tel', models.CharField(max_length=17, validators=[main.models.validate_phone], verbose_name='Номер телефона')),
                ('complete', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_product', models.PositiveIntegerField(verbose_name='Код')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена в евро по курсу НБРБ на дату расчета')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Остаток на конец')),
                ('massa', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Средний вес мешка')),
                ('stock_in_bag', models.PositiveIntegerField(verbose_name='Количество вещей в мешке')),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Средняя себестоимость вещи руб.')),
                ('published_at', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'unique_together': {('number_product', 'title')},
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, verbose_name='Описание видео')),
                ('url', models.URLField(verbose_name='Ссылка для видео')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='main.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
